
Resources:
  dynamoDBTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub ${AWS::StackName}-tablename
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        # Partition Key
        - AttributeName: PK
          KeyType: HASH

        # Sort Key
        - AttributeName: SK
          KeyType: RANGE