AWSTemplateFormatVersion: 2010-09-09
Description: > 
  Template creates an S3 bucket to aggregate CloudTrail Organizational Trail logs. Typically deployed into an Audit account as part of an AWS Organization.


Parameters:   
  pOrganizationId:
    Type: String
    Description: AWS Organization ID. (e.g. o-abcdefghijk)

  pManagementAccountId:
    Type: String
    Description: AWS Account ID of the Organization Management Account

  pManagementAccountTrailName:
    Type: String
    Description: Name of the Organization Management Account's organizational CloudTrail
    Default: cloudtrail-organization

  # Hipaa
  pHipaaClient:
    Type: String
    Description: Client to follow HIPAA compliance (Affects Bucket Lifecycle retention)
    Default: false
    AllowedValues:
      - true
      - false

  # Tagging
  pEnvironmentTag:
    Type: String
    Description: Environment for default resource tagging
    Default: audit
    AllowedValues:
      - production
      - development
      - audit


Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      pHipaaClient:
        default: HIPAA Compliance
      pEnvironmentTag:
        default: Environment Tag
      pManagementAccountId:
        default: Management Account Id
      pManagementAccountTrailName:
        default: Management Account CloudTrail Name
      pOrganizationId:
        default: Organization Id

    ParameterGroups:
      - Label:
          default: Bucket Settings
        Parameters:
          - pHipaaClient
          - pManagementAccountId
          - pManagementAccountTrailName
          - pOrganizationId
      - Label:
          default: Tagging
        Parameters:
          - pEnvironmentTag

Conditions:
  CondHipaa: !Equals [true, !Ref pHipaaClient]


Resources:

  # ====================================
  # Access Logging Bucket - CloudTrail
  # ====================================
  accessLoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub cloudtrail-s3-access-logging-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: access-logs-archive-and-delete
            Status: Enabled
            Transition:
              StorageClass: DEEP_ARCHIVE
              TransitionInDays: 60
            ExpirationInDays: !If [CondHipaa, 2555, 730] #deleted after 2 years if non-HIPAA client. Retained for 7 years if HIPAA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref pEnvironmentTag

  accessLoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Bucket: !Ref accessLoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Allow Sending Access Logs from Source Bucket to this bucket
          - Sid: ServerAccessLogs
            Effect: Allow
            Action:
              - s3:putObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${accessLoggingBucket}/*
            Principal:
              Service: logging.s3.amazonaws.com
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId


  # Bucket Stores CloudTrail logs for all accounts under the AWS Organization
  cloudtrailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub cloudtrail-organization-logs-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref accessLoggingBucket
        LogFilePrefix: !Sub cloudtrail/cloudtrail-organization-logs-${AWS::AccountId}
      LifecycleConfiguration:
        Rules:
          - Id: cloudtrail-logs-archive-and-delete
            Status: Enabled
            Transition:
              StorageClass: DEEP_ARCHIVE
              TransitionInDays: 240
            ExpirationInDays: !If [CondHipaa, 2555, 730] #deleted after 2 years if non-HIPAA client. Retained for 7 years if HIPAA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref pEnvironmentTag

  # https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html
  cloudtrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Bucket: !Ref cloudtrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudtrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:${AWS::Partition}:s3:::${cloudtrailBucket}
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:${AWS::Partition}:cloudtrail:${AWS::Region}:${pManagementAccountId}:trail/${pManagementAccountTrailName}

          - Sid: CloudtrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${cloudtrailBucket}/AWSLogs/${pManagementAccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceArn: !Sub arn:${AWS::Partition}:cloudtrail:${AWS::Region}:${pManagementAccountId}:trail/${pManagementAccountTrailName}


          - Sid: CloudtrailOrganizationWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${cloudtrailBucket}/AWSLogs/${pOrganizationId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceArn: !Sub arn:${AWS::Partition}:cloudtrail:${AWS::Region}:${pManagementAccountId}:trail/${pManagementAccountTrailName}

          - Sid: Restrict Delete* Actions
            Effect: Deny
            Principal: "*"
            Action: s3:Delete*
            Resource: !Sub arn:${AWS::Partition}:s3:::${cloudtrailBucket}/*



Outputs:
  TemplateVersion:
    Value: cloud303-organization-audit-bucket-0.1
    Description: Template Version
